ras_pi_web_app/ras_pi/urls.py
from django.conf.urls import include, url, static
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from api.views import (UserViewSet, ProfileViewSet,
                       ProductViewSet, SaleViewSet,
                       AwsDescriptionViewSet, AwsDescriptionTopThreeViewSet,
                       ApiUserReturnTypeViewSet)

ROUTER = routers.DefaultRouter()
ROUTER.register(r'users', UserViewSet)
ROUTER.register(r'profiles', ProfileViewSet)
ROUTER.register(r'products', ProductViewSet)
ROUTER.register(r'sales', SaleViewSet)
ROUTER.register(r'AwsDescription', AwsDescriptionViewSet)
ROUTER.register(r'AwsDescriptionTopThree', AwsDescriptionTopThreeViewSet)
ROUTER.register(r'ApiUserReturnTypes', ApiUserReturnTypeViewSet)

urlpatterns = [
    url(r'^ras_pi_ui/', include('ras_pi_ui.urls', namespace='ras_pi_ui')),
    url(r'^ras_pi_admin/', include('ras_pi_admin.urls', namespace='ras_pi_admin')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(ROUTER.urls)),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ras_pi_web_app/ras_pi_admin/urls.py
from django.conf.urls import url

from . import views


app_name = 'ras_pi_admin'
urlpatterns = [
    # ex: /ras_pi_admin/
    url(r'^$', views.index, name='index'),
    # ex: /ras_pi_admin/profile_summary/8
    url(r'^profile_summary/(?P<profile_id>[0-9]+)$', views.profile_summary, name='profile_summary'),
    url(r'^product_summary/(?P<product_id>[0-9]+)$', views.product_summary, name='product_summary'),
    url(r'^pay_balance$', views.pay_balance, name='pay_balance'),
    url(r'^restock$', views.restock, name='restock'),
    url(r'^change_price$', views.change_price, name='change_price'),
    url(r'^new_product$', views.new_product, name='new_product'),
    url(r'^new_product_post$', views.new_product_post, name='new_product_post'),
    url(r'^product_list_search$', views.product_list_search, name='product_list_search'),
    url(r'^product_list_search_post$', views.product_list_search_post, name='product_list_search_post'),
    url(r'^profile_list_search$', views.profile_list_search, name='profile_list_search'),
    url(r'^profile_list_search_post$', views.profile_list_search_post, name='profile_list_search_post'),
    url(r'^sale_list$', views.sale_list, name='sale_list'),
]

ras_pi_web_app/ras_pi_admin/models.py
from django.db import models

ras_pi_web_app/ras_pi_admin/views.py
from django.shortcuts import render, Http404, redirect
from ras_pi_ui.models import Profile, Product, Sale

def index(request):
    need_to_pay = get_need_to_pay()
    need_to_restock = get_need_to_restock()
    profiles = Profile.objects.filter(balance__lt=10)[:max((5 - len(need_to_pay)), 0)]
    products = Product.objects.filter(in_stock__gt=5)[:max((5 - len(need_to_restock)), 0)]
    sales = Sale.objects.all()[:5]


    return render(request, 'ras_pi_admin/index.html', {'profiles':profiles,
                                                       'products':products,
                                                       'sales':sales,
                                                       'need_to_restock':need_to_restock,
                                                       'need_to_pay':need_to_pay
                                                       })


def profile_summary(request, profile_id):
    p = Profile.objects.get(pk=profile_id)
    sales_q = Sale.objects.filter(user=p.user)
    sales = []
    for item in sales_q:
        sales.append(item)

    return render(request, 'ras_pi_admin/profile_summary.html', {'profile':p, 'sales':sales})


def product_summary(request, product_id):
    p = Product.objects.get(pk=product_id)
    sales_q = Sale.objects.filter(product=p)
    sales = []
    for item in sales_q:
        sales.append(item)

    return render(request, 'ras_pi_admin/product_summary.html', {'product': p, 'sales': sales})


def pay_balance(request):
    if request.POST:
        param = request.POST
        p = Profile.objects.filter(id=param['profile_id'])[0]
        paid = param['paid']
        p.balance = float(p.balance) - min(float(paid), float(p.balance))
        p.save()
        return redirect('ras_pi_admin:index')
    else:
        raise Http404()


def restock(request):
    if request.POST:
        param = request.POST
        p = Product.objects.get(pk=param['product_id'])
        p.in_stock = int(param['new_stock'])
        p.save()
        return index(request)
    else:
        raise Http404()


def change_price(request):
    if request.POST:
        param = request.POST
        p = Product.objects.get(pk=param['product_id'])
        p.price = float(param['new_price'])
        p.save()
        return index(request)
    else:
        raise Http404()


def new_product(request):
    return render(request, 'ras_pi_admin/new_product.html')


def new_product_post(request):
    r = request.POST
    if r:
        print(r)
        p = Product(name=r['name'], price=r['price'], in_stock=r['stock'])
        p.save()
    else:
        raise Http404()

    return index(request)


def product_list_search(request):
    p = Product.objects.all()
    return render(request, 'ras_pi_admin/product_list_search.html', {'products':p})


def product_list_search_post(request):
    if request.POST:
        search_term = request.POST['search_term']
        p = Product.objects.filter(name__icontains=search_term)
        return render(request, 'ras_pi_admin/product_list_search.html', {'products':p, 'search_term':search_term})
    else:
        raise Http404()


def profile_list_search(request):
    p = Profile.objects.all()
    return render(request, 'ras_pi_admin/profile_list_search.html', {'profiles':p})


def profile_list_search_post(request):
    if request.POST:
        search_term = request.POST['search_term']
        p = Profile.objects.filter(user__username__icontains=search_term)
        return render(request, 'ras_pi_admin/profile_list_search.html', {'profiles':p, 'search_term':search_term})
    else:
        raise Http404()


def sale_list(request):
    s = Sale.objects.all()
    return render(request, 'ras_pi_admin/sale_list.html', {'sales':s})


def get_need_to_pay():
    profile_q = Profile.objects.filter(balance__gte=10)
    profile_lst = []
    for profile in profile_q:
        profile_lst.append(profile)

    return profile_lst


def get_need_to_restock():
    product_q = Product.objects.filter(in_stock__lte=5)
    product_lst = []
    for product in product_q:
        product_lst.append(product)

    return product_lst

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/index.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi admin - Index</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_admin/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>

  {% include 'ras_pi_admin/navbar.html' %}

  <div class="jumbotron col-md-10 col-md-offset-1">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Profiles (<a style="font-size: 14px;" href="{% url 'ras_pi_admin:profile_list_search' %}">View all/Search</a>)</h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for profile in need_to_pay %}
            <li><a style="color:red;" href="{% url 'ras_pi_admin:profile_summary' profile_id=profile.id %}">{{profile}} ({{profile.balance}}$)</a></li>
          {% endfor %}
          {% for profile in profiles %}
            <li><a style="color:#ebebeb;" href="{% url 'ras_pi_admin:profile_summary' profile_id=profile.id %}">{{profile}} ({{profile.balance}}$)</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Products (<a style="font-size: 14px;" href="{% url 'ras_pi_admin:product_list_search' %}">View all/Search</a>)<a style="float:right;background-color:#4e5d6c;padding-left:3px;padding-right:3px;" href="{% url 'ras_pi_admin:new_product' %}">+</a></h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for product in need_to_restock %}
            <li><a style="color:red;" href="{% url 'ras_pi_admin:product_summary' product_id=product.id %}">{{product}} ({{product.in_stock}})</a></li>
          {% endfor %}
          {% for product in products %}
            <li><a style="color:#ebebeb;" href="{% url 'ras_pi_admin:product_summary' product_id=product.id %}">{{product}} ({{product.in_stock}})</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Sales (<a style="font-size: 14px;" href="{% url 'ras_pi_admin:sale_list' %}">View all</a>)</h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for sale in sales %}
            <li>{{sale}}</li>
          {% endfor %}
        </ul>
      </div>
    </div>

  </div>
</body>

</html>

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'ras_pi_admin:index' %}">Ras pi admin</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'ras_pi_admin:profile_list_search' %}">Profiles</a></li>
        <li><a href="{% url 'ras_pi_admin:product_list_search' %}">Products</a></li>
        <li><a href="{% url 'admin:index' %}">App super admin</a></li>
      </ul>
    </div>
  </div>
</nav>

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/new_product.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi admin - New product</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_admin/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>

  {% include 'ras_pi_admin/navbar.html' %}

  <div class="jumbotron col-md-10 col-md-offset-1">
    <form action="{% url 'ras_pi_admin:new_product_post' %}" method="post">
      {% csrf_token %}
      <fieldset>
        <legend>New product</legend>
        <div class="form-group" style="margin-bottom:5%;">
          <label for="inputName" class="col-lg-2 control-label">Name:</label>
          <div class="col-lg-10">
            <input type="text" name="name" class="form-control" id="inputName" placeholder="Name">
          </div>
        </div>
        <div class="form-group" style="margin-bottom:10%;">
          <label for="inputPrice" class="col-lg-2 control-label">Price:</label>
          <div class="col-lg-2">
            <input type="number" name="price" class="form-control" id="inputPrice" value="0" step="0.01" min="0">
          </div>
        </div>
        <div class="form-group" style="margin-bottom:15%;">
          <label for="inputInStock" class="col-lg-2 control-label">Value in stock:</label>
          <div class="col-lg-2">
            <input type="number" name="stock" class="form-control" id="inputInStick" value="0" min="0">
          </div>
        </div>
        <div>
          <div class="col-lg-10 col-lg-offset-2">
            <button class="btn btn-danger" type="reset" id="cancel">Cancel</button>
            <button class="btn btn-success" type="submit" id="ok">OK</button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</body>

</html>

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/product_list_search.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi admin - Products search</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_admin/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>

  {% include 'ras_pi_admin/navbar.html' %}

  <div class="jumbotron col-md-10 col-md-offset-1">

    <form action="{% url 'ras_pi_admin:product_list_search_post' %}" name="search_product_form" method="post">
      {% csrf_token %}
      <div class="form-group">
        <div class="input-group">
          <input type="text" name="search_term" class="form-control" placeholder="search by product name" {% if search_term %}value="{{search_term}}"{% endif %}>
          <span class="input-group-btn">
        <button class="btn btn-success" type="submit">Search</button>
      </span>
        </div>
      </div>
    </form>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Products</h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for product in products %}
            <li><a style="color:#ebebeb;" href="{% url 'ras_pi_admin:product_summary' product_id=product.id %}">{{product}} ({{product.in_stock}})</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

  </div>

</body>

</html>

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/product_summary.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi admin - Product summary</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_admin/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>

  {% include 'ras_pi_admin/navbar.html' %}

  <div class="jumbotron col-md-10 col-md-offset-1">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">{{product.name}}</h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for sale in sales %}
          <li>{{sale}}</li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <form action="{% url 'ras_pi_admin:restock' %}" name="restock_form" method="post">
      {% csrf_token %}
      <div class="form-group col-md-4">
        <label class="control-label">Restock</label>
        <div class="input-group">
          <input type="number" name="new_stock" class="form-control" value="{{product.in_stock}}" min="0">
          <span class="input-group-btn">
            <input type="hidden" name="product_id" value="{{product.id}}">
        <button class="btn btn-success" type="submit">Change</button>
      </span>
        </div>
      </div>
    </form>
    <form action="{% url 'ras_pi_admin:change_price' %}" name="change_price_form" method="post">
      {% csrf_token %}
      <div class="form-group col-md-4">
        <label class="control-label">Change price</label>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <input type="number" name="new_price" class="form-control" value="{{product.price}}" step="0.01" min="0">
          <span class="input-group-btn">
            <input type="hidden" name="product_id" value="{{product.id}}">
        <button class="btn btn-success" type="submit">Change</button>
      </span>
        </div>
      </div>
    </form>

  </div>
</body>

</html>

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/profile_list_search.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi admin - Profiles search</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_admin/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>

  {% include 'ras_pi_admin/navbar.html' %}

  <div class="jumbotron col-md-10 col-md-offset-1">

    <form action="{% url 'ras_pi_admin:profile_list_search_post' %}" name="search_profile_form" method="post">
      {% csrf_token %}
      <div class="form-group">
        <div class="input-group">
          <input type="text" name="search_term" class="form-control" placeholder="search by username" {% if search_term %}value="{{search_term}}"{% endif %}>
          <span class="input-group-btn">
        <button class="btn btn-success" type="submit">Search</button>
      </span>
        </div>
      </div>
    </form>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Profiles</h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for profile in profiles %}
            <li><a style="color:#ebebeb;" href="{% url 'ras_pi_admin:profile_summary' profile_id=profile.id %}">{{profile}} ({{profile.balance}}$)</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>

  </div>

</body>

</html>

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/profile_summary.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi admin - Profile Summary</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_admin/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>

  {% include 'ras_pi_admin/navbar.html' %}

  <div class="jumbotron col-md-10 col-md-offset-1">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">{{profile.user}}</h3>
      </div>
      <div class="panel-body">
        <ul>
          <li>Email:
            <a href="mailto:{{profile.user.email}}?subject=Bill for drinks&body=Your balance is: {{profile.balance}}$.%0D%0APay it to ________ ________%0D%0A%0D%0AThanks%0D%0AThe administration">
              {{profile.user.email}}
            </a>
          </li>
          <li>Name: {{profile.user.first_name}} {{profile.user.last_name}}</li>
          <li>Balance: {{profile.balance}}$</li>
          <li>
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">Sales</h3>
              </div>
              <div class="panel-body">
                <ul>
                  {% for sale in sales %}
                  <li>{{sale}}</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <form action="{% url 'ras_pi_admin:pay_balance' %}" name="pay_balance_form" method="post">
      {% csrf_token %}
      <div class="form-group col-md-4">
        <label class="control-label">Pay balance</label>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <input type="number" name="paid" class="form-control" value="{{profile.balance}}" step="0.01" min="0" max="{{profile.balance}}">
          <span class="input-group-btn">
            <input type="hidden" name="profile_id" value="{{profile.id}}">
        <button class="btn btn-success" type="submit">Pay</button>
      </span>
        </div>
      </div>
    </form>

  </div>
</body>

</html>

ras_pi_web_app/ras_pi_admin/templates/ras_pi_admin/sale_list.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi admin - Sales search</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_admin/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>

  {% include 'ras_pi_admin/navbar.html' %}

  <div class="jumbotron col-md-10 col-md-offset-1">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Sales</h3>
      </div>
      <div class="panel-body">
        <ul>
          {% for sale in sales %}
            <li>{{sale}}</li>
          {% endfor %}
        </ul>
      </div>
    </div>

  </div>

</body>

</html>