ras_pi_web_app/ras_pi/urls.py
from django.conf.urls import include, url, static
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from api.views import (UserViewSet, ProfileViewSet,
                       ProductViewSet, SaleViewSet,
                       AwsDescriptionViewSet, AwsDescriptionTopThreeViewSet,
                       ApiUserReturnTypeViewSet)

ROUTER = routers.DefaultRouter()
ROUTER.register(r'users', UserViewSet)
ROUTER.register(r'profiles', ProfileViewSet)
ROUTER.register(r'products', ProductViewSet)
ROUTER.register(r'sales', SaleViewSet)
ROUTER.register(r'AwsDescription', AwsDescriptionViewSet)
ROUTER.register(r'AwsDescriptionTopThree', AwsDescriptionTopThreeViewSet)
ROUTER.register(r'ApiUserReturnTypes', ApiUserReturnTypeViewSet)

urlpatterns = [
    url(r'^ras_pi_ui/', include('ras_pi_ui.urls', namespace='ras_pi_ui')),
    url(r'^ras_pi_admin/', include('ras_pi_admin.urls', namespace='ras_pi_admin')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(ROUTER.urls)),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ras_pi_web_app/ras_pi_ui/urls.py
from django.conf.urls import url

from . import views


app_name = 'ras_pi_ui'
urlpatterns = [
    # ex: /ras_pi_ui/
    url(r'^$', views.index, name='index'),
    # ex: /ras_pi_ui/picture_taking/
    url(r'^picture_taking/$', views.picture_taking, name="picture_taking"),
    # ex: /ras_pi_ui/auth_positive/
    url(r'^auth_positive/$', views.auth_positive, name="auth_positive"),
    # ex: /ras_pi_ui/profile_summary/
    url(r'^profile_summary/$', views.profile_summary, name="profile_summary"),
    # ex: /ras_pi_ui/register/
    url(r'^register/$', views.register, name="register"),
    url(r'^register_post/$', views.register_post, name="register_post"),
    # ex: /ras_pi_ui/login/
    url(r'^app_login/$', views.app_login, name="app_login"),
    url(r'^app_login_post/$', views.app_login_post, name="app_login_post"),
    # ex: /ras_pi_ui/get_copy_path/
    url(r'^get_copy_path/(?P<key>[0-9A-Za-z]+)$', views.get_copy_path, name="get_copy_path"),
]

ras_pi_web_app/ras_pi_ui/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField('Balance to be paid', max_digits=6, decimal_places=2, default=0)
    reko_face_id = models.CharField(max_length=36, default='')
    reko_desc = models.CharField(max_length=150, default='')

    def __str__(self):
        return self.user.username


class Product(models.Model):
    name = models.CharField(max_length=25)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    in_stock = models.SmallIntegerField('Quantity in stock', default=0)

    def __str__(self):
        return self.name


class Sale(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField('Date purchased', default=timezone.now)

    def __str__(self):
        return str(self.user) + ' --> ' + str(self.product) +\
        ' ( ' + str(self.product.price) + '$ )'


class AwsDescriptionTopThree(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    date = models.TimeField('Date of creation', default=timezone.now)


class AwsDescription(models.Model):
    top_three = models.ForeignKey(AwsDescriptionTopThree, on_delete=models.CASCADE)
    attribute_name = models.CharField(max_length=10)
    attribute_value = models.CharField(max_length=10)

    def __str__(self):
        return str(self.attribute_name) + '-->' + str(self.attribute_value)

ras_pi_web_app/ras_pi_ui/views.py
# -*- coding: utf-8 -*-

import io
import random
import string
from operator import itemgetter
from os import path
from time import sleep
from shutil import copyfile
from picamera import PiCamera, Color
from PIL import Image
import requests

from Rekognition.reko_collection import (add_face_to_collection,
                                         search_faces_from_img, download_profile_img)

from Rekognition.exceptions import NoMatchingFaceException, NoFaceDetectedException
from django.shortcuts import render, redirect, Http404
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.cache import cache
from ras_pi.settings import MEDIA_ROOT
from .models import Profile, Product, Sale, AwsDescription, AwsDescriptionTopThree


camera = PiCamera()
BASE = path.dirname(path.abspath(__file__))
FACE_PICTURE_PATH = MEDIA_ROOT + "/media/new_picture/face_picture.jpg"
FACE_PICTURE_PATH_STATIC = MEDIA_ROOT + "/ras_pi_ui/static/ras_pi_ui/face_picture.jpg"
PROFILE_PICTURE_STATIC = MEDIA_ROOT + "/ras_pi_ui/static/ras_pi_ui/profile_picture.jpg"
RANDOM_KEY = ""

def index(request):
    try:
        if request.user.is_authenticated:
            logout(request)
    except AttributeError:
        pass

    return render(request, 'ras_pi_ui/index.html', {'weather_info': get_weather()})


def get_weather():
    req = requests.get('http://api.openweathermap.org/data/2.5/weather?lat=46.81&lon=-71.22&' +\
                       'units=metric&lang=fr&appid=8974382f7039d2d271a378d92900179f').json()

    weather_info = {'img_id': req['weather'][0]['icon'], 'name': req['name'],
                    'country': req['sys']['country'],
                    'min': str(req['main']['temp_min']), 'max': str(req['main']['temp_max']),
                    'temp': str(req['main']['temp']), 'desc': req['weather'][0]['description']}

    return weather_info


def get_copy_path(request, key):
    if key == RANDOM_KEY:
        return JsonResponse({'path':PROFILE_PICTURE_STATIC})

    return JsonResponse({'error':'Wrong key or no key provided.'})


def picture_taking(request):
    take_picture()
    response = face_recognition_auth(request)
    if response is True:
        return auth_positive(request)
    elif response == 2:
        return register(request)
    elif response == 3:
        return render(request, 'ras_pi_ui/index.html', {'weather_info': get_weather(),
                                                        'no_face':True})


def face_recognition_auth(request):
    byte_img_io = io.BytesIO()

    #ras_pi loading path
    byte_img = Image.open(FACE_PICTURE_PATH)
    #loading path for pc testing
    #byte_img = open_image_for_pc_test()

    byte_img.save(byte_img_io, "PNG")
    byte_img_io.seek(0)
    byte_img = byte_img_io.read()
    return collection_method(byte_img, request)



def auth_positive(request):
    items = Product.objects.all()
    profile = Profile.objects.get(user=request.user)
    return render(request, 'ras_pi_ui/auth_positive.html', {'items': items,
                                                            'f_name':request.user.first_name,
                                                            'l_name':request.user.last_name,
                                                            'desc':profile.reko_desc.split('\n'),
                                                            'login':True})


def profile_summary(request):
    if request.POST:

        product_id = request.POST['product_choice']
        prod = Product.objects.filter(id=product_id)[0]
        profile = Profile.objects.filter(user=request.user)[0]

        new_sale = Sale(product=prod, user=request.user)
        new_sale.save()

        profile.balance += prod.price
        prod.in_stock -= 1
        profile.save()
        prod.save()

        logout(request)

        return render(request, 'ras_pi_ui/profile_summary.html', {'profile':profile,
                                                                  'product':prod})


def app_login(request):
    return render(request, 'ras_pi_ui/login.html')


def app_login_post(request):
    if request.POST:
        param = request.POST
        user = authenticate(request,
                            username=param['inputUsername'],
                            password=param['inputPassword'])

        if user is not None:
            login(request, user)
            return redirect('ras_pi_ui:auth_positive')

        return render(request, 'ras_pi_ui/login.html', {'error':True})


def register(request):
    return render(request, 'ras_pi_ui/register.html')


def register_post(request):
    if request.POST:
        param = request.POST
        email = param['inputEmail']
        first_name = email[:email.index('.')]
        last_name = email[email.index('.')+1:email.index('@')]
        first_name = put_capitals(first_name)
        last_name = put_capitals(last_name)
        user = User.objects.create_user(username=email[:email.index('@')],
                                        email=email, password='qwer1234',
                                        first_name=first_name,
                                        last_name=last_name)
        profile = Profile(user=user)
        profile.save()
        byte_img_io = io.BytesIO()
        # open the raspi image
        byte_img = Image.open(FACE_PICTURE_PATH_STATIC)
        #Pc testing
        #byte_img = open_image_for_pc_test()

        byte_img.save(byte_img_io, "PNG")
        byte_img_io.seek(0)
        byte_img = byte_img_io.read()
        reko_response = add_face_to_collection(byte_img, 'profile_img_'+str(profile.id)+'.png')
        profile.reko_face_id = reko_response['face_id']
        profile.reko_desc = aws_desc_dict_to_string(reko_response['aws_desc_dict'])
        profile.save()
        create_api_data(aws_desc_dict=reko_response['aws_desc_dict'], profile=profile)
        login(request, profile.user)

        return render(request, 'ras_pi_ui/auth_positive.html',
                      {'items' : Product.objects.all(),
                       'f_name': profile.user.first_name,
                       'l_name': profile.user.last_name,
                       'desc'  : profile.reko_desc.split('\n'),
                       'login' : False}
                     )

    else:
        raise Http404()



def take_picture():
    camera.rotation = 270
    camera.resolution = (800, 480)
    camera.annotate_text = "La photo sera prise dans 3 secondes!"
    camera.annotate_foreground = Color('white')
    camera.annotate_text_size = 80
    camera.start_preview()
    sleep(3)
    camera.annotate_text = ""
    camera.capture(FACE_PICTURE_PATH)
    camera.stop_preview()
    copyfile(FACE_PICTURE_PATH, FACE_PICTURE_PATH_STATIC)
    #PC testing
    #return None


def collection_method(img, request):
    try:
        reko_response = search_faces_from_img(img)
        profile = Profile.objects.filter(reko_face_id=reko_response['face_id'])[0]
        profile.reko_desc = aws_desc_dict_to_string(reko_response['aws_desc_dict'])
        profile.save()

        create_api_data(aws_desc_dict=reko_response['aws_desc_dict'], profile=profile)

        #download_profile_img('profile_img_'+str(profile.id)+'.png', PROFILE_PICTURE_STATIC)
        login(request, profile.user)
        return True
    except NoMatchingFaceException:
        return 2
    except NoFaceDetectedException:
        return 3


def key_gen(lenght=32):
    global RANDOM_KEY
    RANDOM_KEY = ''.join(random.choices(string.ascii_letters + string.digits, k=lenght))


def put_capitals(name):
    name = name[0].upper() + name[1:]
    if '-' in name:
        name = name[:name.index('-')+1] + name[name.index('-')+1].upper() + name[name.index('-')+2:]

    return name


def aws_desc_dict_to_string(aws_dict_desc):
    string_desc = 'Age: De ' + str(aws_dict_desc['AgeRange']['Low']) +\
                  ' a ' + str(aws_dict_desc['AgeRange']['High']) + ' ans' +\
                  '\nBarbe: ' + simple_data_to_text(aws_dict_desc['Beard']) +\
                  '\nEmotion: ' + aws_dict_desc['Emotions'][0]['Type'] +\
                  ' (' + str(round(aws_dict_desc['Emotions'][0]['Confidence'], 2)) + '%)' +\
                  '\nLunettes: ' + simple_data_to_text(aws_dict_desc['Eyeglasses']) +\
                  '\nYeux ouverts: ' + simple_data_to_text(aws_dict_desc['EyesOpen']) +\
                  '\nSexe: ' + simple_data_to_text(aws_dict_desc['Gender']) +\
                  '\nBouche ouverte: ' + simple_data_to_text(aws_dict_desc['MouthOpen']) +\
                  '\nMoustache: ' + simple_data_to_text(aws_dict_desc['Mustache']) +\
                  '\nSourire: ' + simple_data_to_text(aws_dict_desc['Smile']) +\
                  '\nLunettes Fumees: ' + simple_data_to_text(aws_dict_desc['Sunglasses'])

    return string_desc


def simple_data_to_text(data):
    return change_bool_to_text(data['Value']) + ' (' + str(round(data['Confidence'], 2)) + '%)'


def change_bool_to_text(bool_value):
    if bool_value is True:
        return 'Oui'
    elif bool_value is False:
        return 'Non'

    return bool_value

def trad_aws_emotion(emotion, gender):
    if emotion == 'HAPPY':
        if gender == 'Female':
            return 'Heureuse'
        return 'Heureux'
    elif emotion == 'SAD':
        return 'Triste'
    elif emotion == 'ANGRY':
        if gender == 'Female':
            return 'Fachee'
        return 'Fache'
    elif emotion == 'CONFUSED':
        if gender == 'Female':
            return 'Confuse'
        return 'Confus'
    elif emotion == 'DISGUSTED':
        if gender == 'Female':
            return 'Degoutee'
        return 'Degoute'
    elif emotion == 'SURPRISED':
        if gender == 'Female':
            return 'Surprise'
        return 'Surpris'

def prepare_api_data_from_aws_desc_dict(aws_desc_dict):
    del aws_desc_dict['AgeRange']
    del aws_desc_dict['Eyeglasses']
    del aws_desc_dict['MouthOpen']

ras_pi_web_app/ras_pi_ui/templates/ras_pi_ui/auth_positive.html
{% load static %}
<!doctype html>
<html>
	<head>
		<title>Authentification réussite</title>
		<link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/bootstrap.min.css' %}">
		<link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
	</head>
	<body>
		<div id="content">
				<div class="inner_center">
					<div class="col-md-6 col-sm-6">
						<img id="taken_picture" src="{% static 'ras_pi_ui/face_picture.jpg' %}" alt="taken picture" />
					</div>
					<div style="height: 238.8px;" class="col-md-6 col-sm-6">
						<ul class="aws_desc">
							{% for line in desc %}
								<li>{{ line }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
				<h2 class="text_center">{{ f_name }} {{ l_name }}</h2>
				<div class="alert alert-dismissible alert-success">
  				<strong>Wow!</strong> La reconnaissance faciale vous a reconnu.<br>
				</div>

				<div id="item_selection_control">
					<form action="{% url 'ras_pi_ui:profile_summary' %}" name="purchaseForm" method="post">
            {% csrf_token %}
						{% if items %}
							<select name="product_choice" id="product_selector">
								{% for item in items %}
									<option value="{{ item.id }}">{{ item.name }} ({{ item.in_stock }})</option>
								{% endfor %}
							</select>
						{% endif %}
						<button id="ok" type="submit">OK</button>
						<a class="btn btn-lg btn-danger" href="{% url 'ras_pi_ui:index' %}" style="vertical-align:top;">cancel</a>
					</form>
				</div>

		</div>
	</body>
</html>

ras_pi_web_app/ras_pi_ui/templates/ras_pi_ui/index.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Ras pi ui - Index</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/bootstrap.min.css' %}">
  <script src="{% static 'script/load_script.js' %}" defer></script>
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>
  <div id="content">
    <div class="alert alert-dismissible alert-info" {% if no_face %}style="display:none;"{% endif %}>
      <strong>Hey!</strong> Appuyer sur le bouton pour vous identifier!
    </div>
    {% if no_face %}
      <div class="alert alert-dismissible alert-danger">
        <strong>Oops!</strong> Il n'y avait pas de visage dans la photo. Veuillez réessayer!
      </div>
    {% endif %}

    <div id="weather_api" class="inner_center">
      <ul class="color_black">
        <li>{{weather_info.name}}, {{weather_info.country}}</li>
        <li><img id="weather_img" src="http://openweathermap.org/img/w/{{weather_info.img_id}}.png" alt="condition actuelle" title="current_condiction" /></li>
				<li>min/max: {{weather_info.min}} °C/{{weather_info.max}} °C</li>
        <li>{{weather_info.temp}} °C</li>
        <li>{{weather_info.desc}}</li>
      </ul>
    </div>
    <form action="{% url 'ras_pi_ui:picture_taking' %}" method="post">
      {% csrf_token %}
      <button id="ok" type="submit">Prendre la photo</button>
    </form>
  </div>
  <div id="loader-cover-bg" hidden>
    <div id="loader"></div>
  </div>
</body>

</html>

ras_pi_web_app/ras_pi_ui/templates/ras_pi_ui/login.html
{% load static %}
<!doctype html>
<html>
	<head>
		<title>Login</title>
		<link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/bootstrap.min.css' %}">
		<link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
	</head>
	<body>
		<div id="content_register">
			<div class="alert alert-dismissible alert-danger">
  			<strong>Oh snap!</strong> The facial recognition haven't recognize you, sign up!
				{% if error %}
					<br>
					<strong>Wrong Login!!!!</strong>
				{% endif %}
			</div>
      <!-- Add params to send -->
			<form class="form-horizontal" action="{% url 'ras_pi_ui:app_login_post' %}" method="post">
        {% csrf_token %}
  			<fieldset>
    			<legend>Login</legend>
					<div>
      			<label for="inputUsername" class="col-lg-2 control-label">Username</label>
      			<div>
        			<input type="text" class="form-control register_input" id="inputUsername" name="inputUsername" placeholder="Username">
      			</div>
    			</div>
    			<div>
      			<label for="inputPassword" class="col-lg-2 control-label">Password</label>
      			<div>
        			<input type="password" class="form-control register_input" id="inputPassword" name="inputPassword" placeholder="Mot de passe">
      			</div>
    			</div>
    			<div>
      			<div class="col-lg-10 col-lg-offset-2">
        			<button type="reset" id="cancel">Cancel</button>
        			<button type="submit" id="ok">OK</button>
      			</div>
    			</div>
  			</fieldset>
			</form>
		</div>
	</body>
</html>

ras_pi_web_app/ras_pi_ui/templates/ras_pi_ui/profile_summary.html
{% load static %}
<!doctype html>
<html>

<head>
  <title>Résumé de profile</title>
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/bootstrap.min.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
</head>

<body>
  <div id="content">
    {% if profile %}
        <h2>{{profile.user.first_name}} {{profile.user.last_name}}</h2>
        <p>Produit: {{product.name}}</p>
        <p>Prix: {{product.price}}$</p>
        <p>Balance: {{profile.balance}}$</p>
    {% endif %}
    <a href="{% url 'ras_pi_ui:index' %}" class="btn btn-success">Retourner à l'accueil</a>
  </div>
</body>

</html>

ras_pi_web_app/ras_pi_ui/templates/ras_pi_ui/register.html
{% load static %}
<!doctype html>
<html>
	<head>
		<title>Ras pi ui - Register</title>
		<link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'ras_pi_ui/bootstrap.min.css' %}">
		<link rel='shortcut icon' type='image/x-icon' href="{% static 'ras_pi_ui/favicon.ico' %}" />
	</head>
	<body>
		<div id="content_register">
			<div class="alert alert-dismissible alert-danger">
  			<strong>Oh snap!</strong> La reconnaissance faciale ne vous a pas reconnu, creez un compte!
			</div>
      <!-- Add params to send -->
			<form class="form-horizontal" action="{% url 'ras_pi_ui:register_post' %}" method="post">
        {% csrf_token %}
  			<fieldset>
    			<legend>Register</legend>
					<div style="margin-top:8%;">
						<label for="inputEmail" class="col-lg-2 control-label">Email</label>
						<div>
							<input type="text" class="form-control register_input" id="inputEmail" name="inputEmail" placeholder="me@lacapitale.com">
						</div>
					</div>
    			<div>
      			<div class="col-lg-10 col-lg-offset-2" style="margin-top:12%;">
							<a class="btn btn-lg btn-danger" href="{% url 'ras_pi_ui:index' %}" style="vertical-align:top;">cancel</a>
        			<button type="submit" id="ok">OK</button>
      			</div>
    			</div>
  			</fieldset>
			</form>
		</div>
	</body>
</html>